ramls/note.json
ramls/note.raml

The consistent method for $ref enables all raml-related tools to operate.

FOLIO-573 pathname schema key

---

scripts/lint-raml-cop.sh

Move into scripts directory.
Enable configuration of sub-directories to avoid, e.g. raml-util

FOLIO-1027 lint raml cop sh 2

---

NEWS.md
pom.xml

* MODNOTES-31 "readonly" fields like creatorUserName, etc should be ignorable
* MODNOTES-34 Update the 'domain-models-runtime' dependency version
* MODNOTES-37 GET /notes/_self requires unexpected permission
* MODNOTES-15 Query validation
* MODNOTES-39 Fix invalid UUIDs
* general tightening of error responses, using RMB's helpers where possible
* Code cleanup

Release 2.1.0

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/rest/impl/NoteTypesImpl.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesTestUtil.java
src/test/java/org/folio/rest/impl/TestUtil.java
src/test/resources/post_note_type.json

Due to https://issues.folio.org/browse/MODNOTES-60 we are expecting to get an individual note type by `/note-type/{typeId}` endpoint
* updated ModuleDescriptor with `note-types` interface and related permissions
* updated `schema.json` file to have `_id` column
* added implementation for GET `/note-types/{typeId}` endpoint
* added tests for `/note-types/{typeId}` and also sample tests for other not implemented yet endpoints to pass Sonar quality gate
[ ] - define  if `permissionsDesired` property needed to be established
- functionality for `"usage"` note type property will be added in further stories related to mod-notes

MODNOTES-60 - Implement GET type endpoint

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/NoteTypesImpl.java
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesTestUtil.java
src/test/resources/post_note.json
src/test/resources/put_note.json

Implement PUT /notes-types/{id} endpoint
* updated ModuleDescriptor
* added implementation for PUT /notes-types/{id} endpoint
* added tests
- this PR should be merged after https://github.com/folio-org/mod-notes/pull/75

MODNOTES-62 Update note type

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/test/java/org/folio/rest/impl/NoteTypesTestUtil.java
src/test/java/org/folio/rest/impl/NotesTest.java

Refactor permission logic
Replace permission logic with permissionRequired declaration in ModuleDescriptor, 
All endpoints return 401 exception if notes.domain.all is missing, so it makes sense to make this permission required and remove checks for this permission from code.

MODNOTES-65 Remove permission logic

---

descriptors/ModuleDescriptor-template.json
ramls/examples/link/noteLinksPut.json
ramls/link.raml
ramls/types/link/noteLinkPut.json
ramls/types/link/noteLinksPut.json

Jira: MODNOTES-69
Add endpoint that allows updating certain note links for an entity,
by sending list of note ids with status "ASSIGNED/UNASSIGNED",
If status is ASSIGNED, entity will be added as a link to certain note,
If status is UNASSIGNED, entity will be removed from list of links of a note
Add raml changes for https://issues.folio.org/browse/MODNOTES-69
Use second approach from https://issues.folio.org/browse/MODNOTES-69 - 
"(2) PUT request which accepts a list of notes and status"
Pass entity information through url path: /note-links/domain/{domain}/type/{type}/id/{id}
because for first approach UI needs to know list of all previously assigned links for an entity (for example if user searches for all unassigned links and decides to assign some of them, UI will first have to send an …

MODNOTES-69: Add raml definition for bulk note link update

---

ramls/note.raml
ramls/types.raml
src/main/java/org/folio/rest/impl/NoteTypesImpl.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java

MODNOTES-86
Add validation for UUID to get by id endpoints
Check if note-type exists before adding it to database
Make error messages more informative
Check if noteType exists before adding it to database
Add validation for UUID for "get note by id" and "get note type by id" endpoints
Fix a warning in tests

MODNOTES-86: Make error messages more informative

---

descriptors/ModuleDescriptor-template.json
ramls/examples/note.sample
ramls/examples/noteCollection.sample
ramls/link.raml
ramls/types/notes/link.json
ramls/types/notes/note.json
src/main/java/org/folio/db/model/NoteView.java
src/main/java/org/folio/rest/impl/NoteLinksImpl.java
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/main/resources/templates/db_scripts/create_note_view.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java
src/test/resources/note/note1.json
src/test/resources/note/note2.json
src/test/resources/note/note3.json
src/test/resources/note/note4.json
src/test/resources/note/updateNote4Request.json
src/test/resources/note/updateNote5RequestWithNonExistingTypeId.json
src/test/resources/note/updateNoteRequest.json
src/test/resources/note/updateNoteRequestWithLinks.json
src/test/resources/note/updateNoteRequestWithNoId.json

Per https://issues.folio.org/browse/MODNOTES-89 and https://issues.folio.org/browse/MODNOTES-90, we want to refactor implementation of notes and note-links to be domain specific. 
- Change ramls and json schemas to move domain from pre-existing links to note level
- Adjust code and tests accordingly

MODNOTES-89 & MODNOTES-90: Make notes specific to a domain

---

descriptors/ModuleDescriptor-template.json

Undo the MD change from last commit to add "metadata" to MD: #105
The okapi serving folio-registry needs to be updated.

FOLIO-2003 initial module metadata, undo because old folio-registry

---

README.md
descriptors/ModuleDescriptor-template.json
ramls/types/notes/note.json
run.sh
src/test/java/org/folio/rest/impl/DBTestUtil.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java
src/test/java/org/folio/util/NoteTestData.java
src/test/resources/note/note5LongTitle.json
src/test/resources/note/note6LongContent.json

Due to https://issues.folio.org/browse/MODNOTES-96 we want to add restrictions to note title and content length.
* added database restriction on note title and content limit
* added json schema restriction on note title and content limit
* added tests

MODNOTES-96 - Check note title and detail limit

---

README.md
descriptors/ModuleDescriptor-template.json

Declare additional module metadata in ModuleDescriptor: containerMemory, databaseConnection
[FOLIO-2003](https://issues.folio.org/browse/FOLIO-2003)
(Doing again, now that folio-registry okapi is updated FOLIO-2016.)

FOLIO-2003 initial module metadata 2

---

descriptors/ModuleDescriptor-template.json
ramls/link.raml
src/main/java/org/folio/rest/impl/NoteLinksImpl.java
src/main/java/org/folio/rest/model/Order.java
src/main/java/org/folio/rest/model/Status.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

Regarding https://issues.folio.org/browse/MODNOTES-102
Implementing additional endpoint for GET notes by status and domain
Adding new endpoint GET /note-links/domain/{domain}/type/{type}/id/{id}
Covering particular endpoint by tests.

MODNOTES-102 Add endpoint for searching notes by assignment status

---

pom.xml
src/main/java/org/folio/db/CqlQuery.java
src/main/java/org/folio/note/NoteRepositoryImpl.java
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/main/java/org/folio/type/NoteTypeRepositoryImpl.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/NotesTest.java

Update to RMB 25
Updated POM dependency for RMB to `25.0.1`
Updated POM dependency for folio-service-tools to `1.0.1`. The old `1.0.0` uses RMB24.
Update two places to fill UUID before saving the entity because RMB 25 does not handle that anymore.
Adjust one test case because RMB25 does not support left truncation search anymore.
Rather than asking all modules to fill UUID, maybe we can handle it in one place like `RMB PostgresClient save` method.
The loss of left truncation search could be inconvenient for customers.
N/A

Update to RMB25

---

src/main/java/org/folio/links/NoteLinksConstants.java
src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/main/java/org/folio/model/OrderBy.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

Support sort by link number
Use json_array_length function in postgres to sort notes by the size of "links" array.

MODKBEKBJ-289 Support sort by link number

---

src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/java/org/folio/type/NoteTypeRepositoryImpl.java
src/main/java/org/folio/type/NoteTypeServiceImpl.java
src/main/resources/application.properties
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java

Per [MODNOTES-100](https://issues.folio.org/browse/MODNOTES-100), fix error message when we try to delete a note type.
- use db exception translation to narrow generic db exception to FK violation
- handle FK violation in case of delete to customize the message

MODNOTES-100  Fix error message when we try to delete a note type

---

src/main/java/org/folio/type/NoteTypeServiceImpl.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java

Change the text of error message 
- from "Note type is referenced by note(s) and cannot be deleted"
- to "Note type is assigned to a note(s) and cannot be deleted"

MODNOTES-100 change the message

---

pom.xml
src/main/java/org/folio/note/NoteServiceImpl.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/java/org/folio/type/NoteTypeServiceImpl.java
src/main/java/org/folio/userlookup/UserLookUp.java
src/main/java/org/folio/userlookup/UserLookUpService.java
src/test/java/org/folio/note/NoteServiceImplTest.java
src/test/java/org/folio/userlookup/UserLookUpTest.java

Sanitize user html input
Use Jsoup to remove dangerous tags.
Move UserLookUp functionality to a separate service to make it mockable
in unit tests.
Jsoup is a library that can parse HTML and among other things, delete all tags that are not specified in whitelist of safe tags
https://jsoup.org

MODNOTES-117: Remove dangerous html tags from note content

---

pom.xml
src/main/resources/templates/db_scripts/create_note_type_view.sql
src/main/resources/templates/db_scripts/schema.json

Remove duplication in sql scripts 
Use new "snippetPath" attribute from RMB 27.0.0
According to release notes (https://github.com/folio-org/raml-module-builder/releases/tag/v26.0.0) the major change from 25.0.1 to 26.0.0 is related to changes in audit table, as far as I know mod-notes doesn't directly depend on this table, so this update should be safe, 
Breaking changes for upgrading to 27.0.0 (https://github.com/folio-org/raml-module-builder/releases/tag/v27.0.0) include 
* RMB-318 Database config: Drop deprecated dot (db.port) variables, use underscore (DB_PORT)
* RMB-445 rename HttpStatus.HTTP_VALIDATION_ERROR to HttpStatus.HTTP_UNPROCESSABLE_ENTITY for 422
Those changes should also be safe and not affect mod-notes
There's also an RMB upgrade guide, …

MODNOTES-128: Update RMB to 27.0.0 to use "snippetPath" schema attribute

---

ramls/types/notes/note.json
ramls/types/notetypes/noteTypeItem.json
src/test/java/org/folio/rest/impl/NotesTest.java

Make error message for requests with invalid UUID values more readable
Add UUID validation to schema so that returned error has the same format as in other folio APIs
The new message is 
```
{
"errors": [
{
"message": "must match \"^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$\"",
"type": "1",
"code": "-1",
"parameters": [
{
"key": "id",
"value": "invalid_type_id"
}
]
}
]
}
```

MODNOTES-121: Add UUID validation

---

descriptors/ModuleDescriptor-template.json

Enables ready default deployment.
Refer to [FOLIO-2234](https://issues.folio.org/browse/FOLIO-2234) and [documentation](https://dev.folio.org/guides/module-descriptor/#launchdescriptor-properties).
And with increased Memory setting FOLIO-2250

FOLIO-2234 Add LaunchDescriptor settings 2

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODNOTES-135 FOLIO-2358 manage container memory

---

pom.xml

The update fixes two polymorphic typing issues:
* https://nvd.nist.gov/vuln/detail/CVE-2019-16335
* https://nvd.nist.gov/vuln/detail/CVE-2019-14540
Update jackson-bom, jackson-databind now uses the version provided by bom.

MODNOTES-132: Update jackson to 2.10.0 to fix security vulnerabilities

---

pom.xml

Remove unneccessary and dangerous variable replacement.
See https://issues.folio.org/browse/FOLIO-2548

MODNOTES-140: Fix Maven ${} variable replacement in src/main/resources

---

ramls/link.raml
src/main/java/org/folio/links/NoteLinksConstants.java
src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/main/java/org/folio/model/OrderBy.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

The story is referring to https://issues.folio.org/browse/MODNOTES-144 to add the ability to sort notes by note type
* updated raml file with information about ordering by noteType
* updated existing implementation with ability to sort by noteType
* added tests

MODNOTES-144 - Notes Accordion: Make Note type column heading sortable

---

ramls/types/notes/note.json
src/test/resources/note/note5LongTitle.json

Extend Note title limit to 255 characters
* Update raml definition
* Update test data

MODNOTES-141 Extend Note title limit to 255 characters

---

ramls/link.raml
src/main/java/org/folio/links/NoteLinksConstants.java
src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/main/java/org/folio/model/OrderBy.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

implementation story for https://issues.folio.org/browse/MODNOTES-147
* updated raml file with information about ordering by content
* updated existing implementation with ability to sort by content
* added tests

MODNOTES-147 Make Note title and details column sortable

---

pom.xml
ramls/types/notes/note.json
src/main/java/org/folio/model/NoteView.java
src/main/java/org/folio/note/NoteRepositoryImpl.java
src/main/resources/templates/db_scripts/create_note_view.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/NotesTest.java

Extend note schema to add additional properties. This is to support "popUpOnUser", "popUpOnCheckOut" attributes required by UI to show Note popup on User/Check-out pages.
* update Note json schema to allow for additional properties
* modify note_view to include all potential additional properties
* update Note repository to handle additional properties

MODNOTES-165 Extend note schema to add additional properties 

---

.github/workflows/test-depend.yml

It seems that both workflow files need to be available on the default branch.
(This is a DevOps testing task. Does not need review.)

FOLIO-2913 Workflow api-lint, test dependent workflow 2

---

Jenkinsfile

See [FOLIO-2898](https://issues.folio.org/browse/FOLIO-2898) and https://dev.folio.org/guides/jenkinsfile/#back-end-modules
Use `doApiDoc` in Jenkinsfile. Replaces `publishAPI`.

FOLIO-2898 Use new api-doc CI tool

---

src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/note/HtmlSanitizerTest.java

Allow saving HTML class attribute in note content
Add `class` attribute to whitelist for all tags

MODNOTES-174 Add `class` attribute to whitelist

---

src/main/java/org/folio/notes/controller/NotesController.java
src/test/java/org/folio/notes/controller/NoteControllerTest.java
src/test/java/org/folio/notes/controller/NoteTypesControllerTest.java
src/test/java/org/folio/notes/support/DatabaseHelper.java
src/test/java/org/folio/notes/support/TestApiBase.java

To rewrite tests for Note Service by using spring
- added tests for note service
- rewrite DatabaseHelper by adding common logic
Discuss with team about **location** in the NotesController and NoteTypesController during creation entity. We have diffent behavior for creation location: 
- for note: http://localhost/notes/77777777-7777-7777-7777-777777777777 
- for note-type: /note-types/77777777-7777-7777-7777-777777777777
https://issues.folio.org/browse/MODNOTES-187

MODNOTES-187 Rewrite tests for Notes

---

src/main/java/org/folio/notes/domain/mapper/NoteTypesMapper.java
src/main/java/org/folio/notes/domain/repository/NoteTypeTuple.java
src/main/java/org/folio/notes/domain/repository/NoteTypesRepository.java
src/main/java/org/folio/notes/service/impl/NoteTypesServiceImpl.java
src/test/java/org/folio/notes/controller/NoteTypesControllerTest.java

Responses from GET endpoints of note-types API should include note type usage.
- extend repository by adding search by count of notes
https://issues.folio.org/browse/MODNOTES-192

MODNOTES-192 Calculate note type usage and include it into responses

---

NEWS.md
pom.xml

Fix log4j2 `RCE` vulnerability
- log4j2 version set to 2.16.0
[MODNOTES-194](https://issues.folio.org/browse/MODNOTES-194)
[CVE-2021-44228](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)
[CVE-2021-45046](https://github.com/advisories/GHSA-7rjr-3q55-vv33)
`mvn dependency:tree -Dincludes=org.apache.logging.log4j` can be used to check log4j versions used

MODNOTES-194 Kiwi R3 2021 - Log4j vulnerability verification and correction

---

src/main/java/org/folio/notes/service/impl/ConfigurationServiceImpl.java
src/test/java/org/folio/notes/support/TestApiBase.java

Change module name to NOTES
Change module name in tests and service
https://issues.folio.org/browse/MODNOTES-198

MODNOTES-198 Spring way: rename module name to NOTES

---

.editorconfig

Use backslash line termination, rather than br or double-space
https://dev.folio.org/faqs/how-to-use-editorconfig/

FOLIO-351 .editorconfig: Remove markdown exception

---

src/main/java/org/folio/notes/domain/mapper/NoteCollectionMapper.java

Add  `popUpOnCheckOut`, `popUpOnUser` attributes in `/note-links` api response for users.
- remove `ignore` for popUp attributes in mapper
[MODNOTES-204](https://issues.folio.org/browse/MODNOTES-204)

MODNOTES-204 Missing attributes in api response

---

src/main/resources/application.yaml
src/test/java/org/folio/notes/controller/NoteControllerTest.java
src/test/java/org/folio/notes/controller/NoteTypesControllerTest.java
src/test/java/org/folio/notes/support/TestApiBase.java

Always return `notes` property on `GET /notes` even when there are no items in the property. This is dictated by the FOLIO convention.

MODNOTES-206 Always return `notes` property on GET /notes

---

Dockerfile

Fix jar name in Dockerfile
[MODNOTES-208](https://issues.folio.org/browse/MODNOTES-208)

MODNOTES-208 Fix jar name in Dockerfile

---

src/main/resources/db/changelog/changes/v3.0.0/migrate-data.xml
src/main/resources/db/changelog/changes/v3.0.0/sql/migrate-types.sql
src/test/resources/migration/schema-v2-13-data.sql

Fix migration when userId is undefined
Insert `null` if userId is `undefined` in previous data model

MODNOTES-219 Fix migration when userId is undefined

---

pom.xml
src/test/java/org/folio/notes/controller/NoteControllerTest.java
src/test/java/org/folio/notes/controller/NotesControllerTest.java

As described [MODNOTES-244](https://issues.folio.org/browse/MODNOTES-244), GET /notes type.id=X was failing if limit <= number of results
The root cause is found and fixed in scope of [FOLSPRINGB-72](https://issues.folio.org/browse/FOLSPRINGB-72)

MODNOTES-244 - GET /notes type.id=X fails if limit <= number of results

---

NEWS.md
pom.xml

Upgrade to folio-spring-base v5.0.0
https://issues.folio.org/browse/MODNOTES-247

MODNOTES-247 - Upgrade to folio-spring-base v5.0.0

---

src/main/java/org/folio/notes/service/impl/NotesServiceImpl.java
src/main/resources/application.yaml
src/main/resources/swagger.api/notes.yml
src/test/java/org/folio/notes/controller/NotesControllerTest.java
src/test/resources/application-test.yaml

Changed the limit of the maximum number of records returned per request to reduce the risk of a recurrence of the problem with OutOfMemoryError.
Set upped the limit of 1000 records.

MODNOTES-255 changed maximum records limit value.

---

Dockerfile
pom.xml

https://issues.folio.org/browse/MODNOTES-260
Upgrade spring-boot-starter-parent from 3.0.2 to 3.0.5.
Upgrade Alpine packages to the latest patch version.

MODNOTES-260: Spring Boot 3.0.5, upgrade Alpine

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
src/main/resources/swagger.api/notes.yml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODNOTES-265 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Review and cleanup Module Descriptors 
Permissions of the notes interface changed:
notes.domain.all permissions deleted (it’s not required anymore)
notes.collection.get.by.status permission renamed to note.links.collection.get
https://folio-org.atlassian.net/browse/MODNOTES-269

build: update permissions for notes interface
