folio-org/mod-notes

ModuleDescriptor.json
descriptors/ModuleDescriptor-template.json

Update module descriptor and mod descr template to add permissions.

---

run.sh

Cleanup run sh

---

Jenkinsfile

test new Jenkinsfile and pipeline library branch in master.

Folio 932 test

---

lint-raml-cop.sh

Find and process raml files, schema, and examples.
Report issues and lead to help.

FOLIO-1027 Add lint-raml-cop.sh

---

run.sh
src/test/java/org/folio/rest/impl/NotesTest.java
src/test/resources/mock_content.json

Some UUIDs are invalid. See https://en.wikipedia.org/wiki/Universally_unique_identifier
For a UUID xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx M must be 1-5 and N must be 8, 9, a or b.

MODNOTES-39: Fix invalid UUIDs

---

Jenkinsfile
README.md

This mod-notes is referred to in documentation. Update its Jenkinsfile syntax to use the new style "true or false".

Update jenkinsfile syntax

---

pom.xml
src/test/java/org/folio/rest/impl/NotesTest.java

One unit test had to be updated to due to change of returned
status code due to RMB-293 work.

Upgrade to RMB 23.11.0, mod-notify 2.2.0 MODNOTES-47

---

pom.xml
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/test/java/org/folio/rest/impl/DBTestUtil.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java

Make tests more maintainable by splitting them into separate test methods
Create necessary notes before each test and delete all notes after each test

MODNOTES-65 split note tests

---

pom.xml

Adding path for downloading all needed schemas

Adding downloading path for json schemas

---

src/main/java/org/folio/rest/impl/NoteTypesImpl.java
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/main/java/org/folio/type/NoteTypeRepository.java
src/test/java/org/folio/rest/impl/NotesTest.java

Simplify interactions with PostgresClient by using io.vertx.core.Future
Refactor CompletableFuture into vertx Future

Use vertx future for database interactions

---

ramls/types/notes/note.json
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/main/java/org/folio/userlookup/UserLookUp.java
src/main/resources/templates/db_scripts/check_type_id.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java
src/test/java/org/folio/userlookup/UserLookUpTest.java

Refactor existing PUT /notes{id } endpoint  https://issues.folio.org/browse/MODNOTES-67 
* updated logic for PUT /note/{id}
* updated tests

MODNOTES-67 - Notes: Support note update

---

README.md
ramls/types/notes/note.json
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/main/java/org/folio/userlookup/UserLookUp.java
src/test/java/org/folio/rest/impl/NotesTest.java

Updates due to  https://issues.folio.org/browse/MODNOTES-66
* updated existing implementation of POST /notes - used existing UserLookUp class to fetch used data
* updated note.json file - removed `content` from required fields
* modified tests to include assertThat() call to fix Sonar issues
* updated NEWS.md file - to maintain consistency between current implementation and documentation

MODNOTES-66 - Notes: Support create new note

---

src/main/java/org/folio/rest/impl/NoteTypesImpl.java
src/main/resources/templates/db_scripts/create_note_type_view.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java
src/test/resources/post_note.json
src/test/resources/post_note_type.json
src/test/resources/put_note.json
src/test/resources/put_note_type.json

According to https://issues.folio.org/browse/MODNOTES-72
Note type details should contain the number of related notes.
Creating note_type_view which collect and calculate all data needed.

MODNOTES-72 Notes: calculate and return note type usage

---

src/main/resources/templates/db_scripts/check_type_id.sql
src/main/resources/templates/db_scripts/schema.json

Per https://issues.folio.org/browse/MODNOTES-92, module enabling was failing due to SQL exceptions. This PR addresses those issues.
- Add column and create trigger only if they do not exist already.

MODNOTES-92: Update SQL to fix exceptions

---

README.md
descriptors/ModuleDescriptor-template.json
pom.xml
run.sh

Updates for https://issues.folio.org/browse/MODNOTES-97
* updated Module Descriptor
* updated Readme file
* changed module group id to be same as for other modules

MODNOTES-97 - Modify ModuleDescriptor

---

src/main/java/org/folio/rest/impl/NoteTypesImpl.java

Fixing tests fails.
https://issues.folio.org/browse/MODNOTES-98
Adding validate annotation.

MODNOTES-98 Failing API tests

---

NEWS.md
pom.xml

Create revised Q2.1 release which includes the following changes
* https://issues.folio.org/browse/MODNOTES-97 - Modify Module Descriptor, Dependencies and group id
* https://issues.folio.org/browse/MODNOTES-98 - Fix failing API Tests - missing validate annotation

Release 2.4.0 (Q2.1 updated)

---

pom.xml
src/main/java/org/folio/rest/exc/ExceptionHandlers.java
src/main/java/org/folio/rest/impl/NotesResourceImpl.java

Looks like notify is no longer in use (as seen from module descriptor change)

Update to RMB 24 / remove notify dep MODNOTES-101

---

ramls/link.raml
src/main/java/org/folio/rest/impl/NoteLinksImpl.java
src/main/java/org/folio/rest/model/OrderBy.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

Add ability to filter and sort by title
Calculate totalRecords
Construct sql query dynamically using StringBuilder

MODNOTES-102 Extend GET /note-links endpoint

---

src/main/java/org/folio/db/CqlQuery.java
src/main/java/org/folio/note/NoteRepository.java
src/main/java/org/folio/note/NoteRepositoryImpl.java
src/main/java/org/folio/note/NoteService.java
src/main/java/org/folio/note/NoteServiceImpl.java
src/main/java/org/folio/rest/exceptions/InputValidationException.java
src/main/java/org/folio/rest/exceptions/NoteExceptionHandlers.java
src/main/java/org/folio/rest/impl/NotesResourceImpl.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/java/org/folio/type/NoteTypeRepositoryImpl.java
src/main/java/org/folio/userlookup/UserLookUp.java
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/rest/impl/NotesTest.java

Refactor NotesResourceImpl to use endpoint/service/repository layers,
Simplify code by using folio-service-tools-dev library
Move code specific to database to NoteRepositoryImpl
Move code related to business logic to NoteServiceImpl
Refactor NotesResourceImpl to use exceptionHandler
Note: For now NoteRepositoryImpl throws exceptions NotFoundException, BadRequestException. Those exceptions are specific to http, so we might want to create separate exceptions for database layer

MODNOTES-105 refactor NotesResourceImpl

---

src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

Fixing incorrect working of sort
Incorrect query has been created. Sorting parameters have not been adding to particular query in current case.

MODNOTES-110 Note Links: Sorting doesn't work as expected for status = assigned/unassigned

---

src/main/java/org/folio/rest/impl/NoteTenantApiImpl.java
src/main/resources/application.properties
src/test/java/org/folio/rest/impl/NoteTenantApiImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java

Add default note type
Extend TenantApi to add note type when tenant is created/updated

MODNOTES-109 Add default note type

---

src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

Add the ability to search notes by using partial search words, for example search for "acad*" should return notes with word academic in the title
Replace "\*" characters in input with ".\*" regular expression, escape all other special characters

MODNOTES-111: Add wildcard support to note search

---

ramls/link.raml
src/main/java/org/folio/links/NoteLinksConstants.java
src/main/java/org/folio/links/NoteLinksRepository.java
src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/main/java/org/folio/links/NoteLinksService.java
src/main/java/org/folio/links/NoteLinksServiceImpl.java
src/main/java/org/folio/rest/impl/NoteLinksImpl.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java
src/test/java/org/folio/rest/impl/NoteTypesImplTest.java
src/test/java/org/folio/util/NoteTestData.java

Per https://issues.folio.org/browse/MODKBEKBJ-290 we would like to add additional search parameter - note type.
* updated raml definition to add filtering by note type
* updated Note Links implementation for searching by note type
* added tests

MODKBEKBJ-290 - Ability to filter by notes types

---

NEWS.md
pom.xml

Release 2.6.0

---

pom.xml

Due to  https://issues.folio.org/browse/MODKBEKBJ-296 jackson lib should be upgraded.

Upgrading jackson lib

---

src/main/java/org/folio/rest/exceptions/NoteExceptionHandlers.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/test/java/org/folio/rest/impl/NotesTest.java

Per https://issues.folio.org/browse/MODNOTES-119 make error message more readable
* added handler for CQLQueryValidationException
* adjusted tests

MODNOTES-119 - Fix error message for quering notes

---

src/main/java/org/folio/note/NoteServiceImpl.java
src/test/java/org/folio/note/NoteServiceImplTest.java
src/test/java/org/folio/util/NoteTestData.java
src/test/resources/note/note6EmptyContent.json

Fix for  issue https://issues.folio.org/browse/MODNOTES-124 
* fixed NPE in case of no note content provided for POST and PUT requests
* added tests for empty and not existing note content.

MODNOTES-124 - Internal server error during creation of the note

---

descriptors/ModuleDescriptor-template.json

test via Jenkins folio-testing-test failed

FOLIO-2234 Restore LaunchDescriptor settings

---

NEWS.md
pom.xml

Release 2.7.0

---

pom.xml

fix for https://issues.folio.org/browse/MODNOTES-131
* updated rmb version

MODNOTES-131 - Upgrade RMB to 27.1.1

---

pom.xml
src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/main/java/org/folio/note/NoteRepositoryImpl.java
src/main/java/org/folio/rest/impl/NoteTenantApiImpl.java
src/main/java/org/folio/rest/impl/NotesImpl.java
src/main/java/org/folio/type/NoteTypeRepositoryImpl.java
src/main/java/org/folio/userlookup/UserLookUpService.java

Update RMB version to 29.0.1
Change usage of vertx Future to vertx Promise
Use version folio-service-tools that supports RMB 29.0.1

MODNOTES-136: Update RMB version to 29.0.1

---

src/main/resources/templates/db_scripts/schema.json

Set fromModuleVersion attribute

MODNOTES-137: Set fromModuleVersion attributes

---

ramls/link.raml
src/main/java/org/folio/links/NoteLinksConstants.java
src/main/java/org/folio/links/NoteLinksRepositoryImpl.java
src/main/java/org/folio/model/Order.java
src/main/java/org/folio/model/OrderBy.java
src/test/java/org/folio/rest/impl/NoteLinksImplTest.java

implementation story for https://issues.folio.org/browse/MODNOTES-146
* updated raml file with information about ordering by updatedDate
* updated existing implementation with ability to sort by updatedDate
* added tests

MODNOTES-146 - Notes Accordion: Make Date column heading sortable

---

pom.xml
src/main/java/org/folio/type/NoteTypeRepositoryImpl.java

MODNOTES-153 mod-notes: Update to RMB v31.x

---

src/main/java/org/folio/note/HtmlSanitizer.java
src/main/java/org/folio/note/NoteServiceImpl.java
src/main/java/org/folio/note/Sanitizer.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/note/HtmlSanitizerTest.java

Fix note content sanitizing
* Create `Whitelist` for supported tags and attributes
* Diable pretty printing for HTML sanitizer

MODNOTES-158 Fix note content sanitizing

---

src/main/resources/templates/db_scripts/create_note_search_column.sql

Add safety check to `search_content_idx_gin` create statement

MODNOTES-165 Add safety check to search_content_idx_gin create statement

---

PERSONAL_DATA_DISCLOSURE.md

Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
* add PERSONAL_DATA_DISCLOSURE.md file

MODNOTES-171 Add personal data disclosure form

---

Jenkinsfile

FOLIO-3224 verify changes in jenkins-pipeline-libs

---

descriptors/ModuleDescriptor-template.json

Fix permissions for note-types
Add required module permissions

MODNOTES-190 Fix permissions for note-types

---

CODEOWNERS
src/main/java/org/folio/notes/service/impl/NotesServiceImpl.java
src/test/java/org/folio/notes/controller/NoteControllerTest.java
src/test/java/org/folio/notes/support/DatabaseHelper.java

Added test case for links, update logic for removing note if note doesn't have any link
Write test case for Links, added logic for removing notes if note doesn't contain link
https://issues.folio.org/browse/MODNOTES-186

MODNOTES-186 Rewrite tests for NoteLinks

---

src/main/java/org/folio/notes/config/hibernate/ExtendedPostgreSQL10Dialect.java
src/main/java/org/folio/notes/config/hibernate/predicate/ILikePredicate.java
src/main/java/org/folio/notes/domain/repository/NoteRepository.java
src/main/resources/application.yaml
src/test/java/org/folio/notes/controller/NoteControllerTest.java

Support case-insensitive notes search
* Extend PostgreSql dialect with ilike predicate

MODNOTES-193 Support case-insensitive notes search

---

src/main/java/org/folio/notes/domain/mapper/NoteTypesMapper.java

Fix NPE in the mapper
Add verification during calculation notes
https://issues.folio.org/browse/MODNOTES-199

MODNOTES-199 Spring way: error during calculate notes

---

pom.xml
src/main/java/org/folio/notes/controller/NoteTenantController.java
src/test/java/org/folio/notes/support/TestApiBase.java

MODNOTES-201 Upgrade spring-base

---

src/main/java/org/folio/notes/service/impl/NotesServiceImpl.java
src/test/java/org/folio/notes/controller/NoteControllerTest.java

Fix 500 error on changing note type for note on PUT request.
- fix note type changing
- add test cases
[MODNOTES-205](https://issues.folio.org/browse/MODNOTES-205)

MODNOTES-205 Changing note type returns 500 code

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/notes/client/ConfigurationClient.java
src/main/java/org/folio/notes/service/impl/ConfigurationServiceImpl.java
src/test/java/org/folio/notes/controller/NoteTypesControllerTest.java
src/test/java/org/folio/notes/support/TestApiBase.java

Handle configuration client exception
https://issues.folio.org/browse/MODNOTES-214

MODNOTES-214 Permissions error with settings.notes.enabled 

---

src/main/resources/db/changelog/changes/v3.0.0/cleanup-rmb.xml

Update RMB-cleanup scripts with specifying the schema. Use ${database.defaultSchemaName} where you need schema name
Use ${database.defaultSchemaName}
[MODNOTES-215](https://issues.folio.org/browse/MODNOTES-215)

MODNOTES-215 Update RMB-cleanup scripts with specifying the schema

---

src/main/resources/db/changelog/changes/v3.0.0/sql/migrate-note-links.sql

Boost migration process
- improve note-links migration script
[MODNOTES-218](https://issues.folio.org/browse/MODNOTES-218)

MODNOTES-218 Migration Issue from Kiwi-Lotus

---

src/main/resources/db/changelog/changes/v3.0.0/migrate-data.xml

Fix update mod-notes from 3.0.0 to 3.0.x
- add runOnChange="true" for note-links changeSet
[MODNOTES-221](https://issues.folio.org/browse/MODNOTES-221)

MODNOTES-221 Update mod-notes from 3.0.0 to 3.0.1 failed

---

Jenkinsfile

https://issues.folio.org/browse/MODNOTES-223
https://dev.folio.org/guides/jenkinsfile/#back-end-modules
https://issues.folio.org/browse/FOLIO-3407

MODNOTES-223: Jenkinsfile healthChkCmd: Prefer wget over curl

---

src/main/java/org/folio/notes/domain/entity/NoteTypeEntity.java
src/main/java/org/folio/notes/domain/entity/projection/NoteTypeCount.java
src/main/java/org/folio/notes/domain/mapper/NoteTypesMapper.java
src/main/java/org/folio/notes/domain/repository/NoteTypesRepository.java
src/main/java/org/folio/notes/service/impl/NoteTypesServiceImpl.java
src/main/resources/application.yaml
src/test/java/org/folio/notes/controller/NoteTypesControllerTest.java

Improve note type count calculation
* Move count calculation to database level

MODNOTES-224 Improve note type count calculation

---

NEWS.md
pom.xml

- Release mod-notes [v3.1.1](https://github.com/folio-org/mod-notes/releases/tag/v3.1.1)
- Update news
https://issues.folio.org/browse/MODNOTES-238

MODNOTES-238 Release mod-notes v3.1.1 Morning Glory BF (R2 2022)

---

README.md
docs/api-guide.md
src/test/java/org/folio/notes/controller/NotesControllerTest.java
src/test/java/org/folio/notes/support/DatabaseHelper.java

Create documentation for supported CQL queries
* update documentation
* update tests

MODNOTES-243 Update module docs and add tests

---

docs/api-guide.md

MODNOTES-245 Fix API docs

---

NEWS.md
docs/RELEASES.md
pom.xml

Relase v4.0.0
[MODNOTES-246](https://issues.folio.org/browse/MODNOTES-246)

Tmp release v4.0

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/application.yaml

_Logging should be improved for more productive troubleshooting._
- Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
- Enable the /loggers endpoint in our application.properties file by adding the following lines:
- management.endpoints.web.exposure.include=loggers
- management.endpoint.loggers.enabled=true
- The version of the folio-spring-base should be updated (see [FOLSPRINGB-45](https://issues.folio.org/browse/FOLSPRINGB-45))
- Add step "Check logging" to PULL_REQUEST_TEMPLATE.md
https://issues.folio.org/browse/MODNOTES-250

MODNOTES-250 - Logging improvement - Configuration

---

src/main/java/org/folio/notes/service/impl/ConfigurationServiceImpl.java
src/main/java/org/folio/notes/service/impl/NoteTypesServiceImpl.java
src/main/java/org/folio/notes/service/impl/NotesServiceImpl.java
src/main/java/org/folio/notes/service/impl/UsersServiceImpl.java

_Logging improvement for more productive troubleshooting._
_Added logs in branching and conditions_
- There were no big changes like API, datasource or logic that affects versioning

MODNOTES-209: Improve logging

---

pom.xml

Update folio-spring-base to 6.0.2

MODNOTES-256  Update folio-spring-base to 6.0.2

---

NEWS.md

- Update NEWS 
- Release v5.0.1

MODNOTES-257 Update NEWS v5.0.1

---

Jenkinsfile

Test maven 3.8.8 deployment to Nexus repo.

Maven388 test

---

pom.xml

spring-support-upgrade
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._

deps: spring-support-upgrade

---

Dockerfile
Jenkinsfile
NEWS.md
pom.xml
src/main/java/org/folio/notes/service/impl/ConfigurationServiceImpl.java
src/test/java/org/folio/notes/controller/NotesControllerIT.java

Upgrade to Java 21
https://folio-org.atlassian.net/browse/MODNOTES-273

chore: upgrade to Java 21

---

NEWS.md
pom.xml
src/main/java/org/folio/notes/service/impl/NotesServiceImpl.java
src/main/resources/application.yaml
src/test/java/org/folio/notes/controller/NotesControllerIT.java
src/test/java/org/folio/notes/support/DatabaseHelper.java
src/test/java/org/folio/notes/support/TestApiBase.java

Prepare for next development iteration 7.1.0

Prepare for next development iteration 7.1.0

---

NEWS.md
src/main/java/org/folio/notes/controller/ErrorHandling.java
src/main/java/org/folio/notes/exception/NoteTypesLimitReached.java
src/main/java/org/folio/notes/util/ErrorsHelper.java
src/test/java/org/folio/notes/controller/NoteTypesControllerIT.java

Update an error message for note types limit reached
Update error handling 
https://folio-org.atlassian.net/browse/MODNOTES-277

feat(note-types): update an error message for note types limit reached
